@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor applicant as applicant
actor admin as admin
participant backend as backend
entity tagContract as tagContract
entity factoryContract as factoryContract
entity brandContract as brandContract
participant alchemy as alchemy

applicant --> backend: apply一个新的brand,并将请求保存在数据库中
admin --> backend: 发现有一个新的brand申请
admin --> backend: approve生成一个新的brand
backend --> factoryContract: createNewBrand()尝试生成新的brand合约
factoryContract --> tagContract: 检查tag数据是否有误
factoryContract --> brandContract: 部署一个新的brand合约
factoryContract --> factoryContract: 将新生成的brand合约信息记录
factoryContract --> factoryContract: 抛出NewBrandEvent
alchemy --> factoryContract:监听到NewBrandEvent
alchemy --> backend: 通知新创建了brand
backend --> backend: 更新数据库中的brand数据

@enduml