@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "any user" as user
participant backend as backend
entity tagContract as tagContract
participant alchemy as alchemy

applicant --> tagContract: mint一个新的tag
tagContract --> tagContract: 新增一个tag并记录
tagContract --> tagContract: 抛出NewTagEvent
alchemy --> tagContract:监听到NewTagEvent
alchemy --> backend: 通知新创建了tag
backend --> backend: 更新数据库中的tag数据

@enduml