@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor applicant as applicant
participant backend as backend
entity tagContract as tagContract
entity brandSetContract as brandSetContract
entity brandContract as brandContract
participant alchemy as alchemy

applicant --> backend: apply一个新的brand,自动签名,并将请求保存在数据库中
applicant --> backend: 发现brand apply已被approve
applicant --> brandContract: 部署新的brand合约
applicant --> brandSetContract: mint一个brand
brandSetContract --> brandSetContract: 检查brand合约是否符合要求
brandSetContract --> brandSetContract: 将新生成的brand合约信息记录
brandSetContract --> brandSetContract: 抛出NewBrandEvent
alchemy --> brandSetContract:监听到NewBrandEvent
alchemy --> backend: 通知新创建了brand
backend --> backend: 更新数据库中的brand数据

@enduml